### ISSUE TITLE
'Command not supported: *' causes infinite chaining of previous commands

### ISSUE THREAD

**Issue by nardeas** [paddyabc/rethinkdb-repl-cli#2]
If you launch the client and type in a command that is not supported this happens:

```
rethinkdb [test]> ls
Command not support: ls
rethinkdb [test]> exit
Command not support: lsexit
```

So making one mistake by typing an unsupported command results in the client being useless, since there's no way to purge the previous command buffer. You will have to restart the client to make it work again.

Tested on: OSX 10.11.1
Node version: 6.7.0

**Comment by paddyabc** [comment]
Thanks for your comments.
Sorry, I am very busy in the past few months and I just notice the issue yesterday.
The bug has been fixed. You can check out the latest version in git or npm.
Thank you very much.
